//
// Created by Владимир Лысенков on 24.06.2020.
//

#ifndef LAN_4GATELIBRARYCPP_RESPONSEDATAFACTORY_H
#define LAN_4GATELIBRARYCPP_RESPONSEDATAFACTORY_H

#endif //LAN_4GATELIBRARYCPP_RESPONSEDATAFACTORY_H
