name: Linux

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        compiler:
          - name: "g++-5"
            package: "g++-5"
          - name: "g++-6"
            package: "g++-6"
          - name: "g++-7"
            package: "g++-7"
          - name: "g++-8"
            package: "g++-8"
          - name: "g++-9"
            package: "g++-9"
          - name: "clang-5.0"
            package: "clang-5.0"
          - name: "clang-6.0"
            package: "clang-6.0"
          - name: "clang-7"
            package: "clang-7"
          - name: "clang-8"
            package: "clang-8"
          - name: "clang-9"
            package: "clang-9"
          - name: "clang-10"
            package: "clang-10"
        build_type: ["Debug", "Release"]

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2

    - name: Add APT repositories
      run: |
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
        sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'

    - name: Install APT dependencies
      run: |
        sudo apt update
        sudo apt install --yes ${{matrix.compiler.package}} git cmake ninja-build

    - name: Configure
      run: |
        cmake -S . -B Build/L4GLibrary -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.compiler.name}} -DL4G_TESTS=ON -G Ninja

    - name: Build and test
      run: |
        cmake --build Build/L4GLibrary
        ctest --test-dir Build/L4GLibrary
