name: macOS

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        build_type: ["Debug", "Release"]

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2

    - name: Install Homebrew dependencies
      run: |
        brew install cmake

    - name: Configure
      run: |
        cmake -S . -B Build/L4GLibrary -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DL4G_TESTS=ON

    - name: Build
      run: |
        cmake --build Build/L4GLibrary
    - name: Test
      run: |
        ctest --test-dir Build/L4GLibrary